### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aliok**

### CODE REVIEW

**Comment by nak3** [comment]
/lgtm

LGTM, but it seems that https://godoc.org/knative.dev/net-certmanager in README is invalid and is failing to build test :cold_sweat:

**Comment by aliok** [comment]
@nak3 mind lgtm'ing again?

Removed the link to godoc.org. It doesn't exist

**Comment by ZhiminXiang** [comment]
/lgtm
/approve

Thanks for fixing it @aliok

**Pull request merged**
